### ISSUE TITLE
is this project still alive? website 502 error, project ship date silently missed and moved to june 2023

### ISSUE THREAD

**Issue by keatonp-inahoodie** [unsurv/unsurv-android#4]
I wanted to buy this device and was very excited when I found it, but noticed that the ship date on crowd supply had just passed a month but your twitter was totally inactive for months before and since even today. And now I see the website is down. Can you provide any sort of update on the status of your project which apparently raised $8,297? Is this even still happening and why the radio silence?

**Comment by unsurv** [comment]
hey, sorry I missed this. You are referring to [unsurv-offline](https://github.com/unsurv/unsurv-offline). Yes the project is still active but has been delayed in part because of Texas Instruments and now I am facing challenges with the certification process of the project. You can read about this is the update I released [here](https://www.crowdsupply.com/unsurv-technologies/unsurv-offline/updates/battery-charger-components-and-current-production-timeline). 

DM me on [Twitter](https://twitter.com/unsurv) I will send you a prototype to play around with.

**Comment by keatonp-inahoodie** [comment]
> hey, sorry I missed this. You are referring to [unsurv-offline](https://github.com/unsurv/unsurv-offline). Yes the project is still active but has been delayed in part because of Texas Instruments and now I am facing challenges with the certification process of the project. You can read about this is the update I released [here](https://www.crowdsupply.com/unsurv-technologies/unsurv-offline/updates/battery-charger-components-and-current-production-timeline).
> 
> DM me on [Twitter](https://twitter.com/unsurv) I will send you a prototype to play around with.

omg what, thank you so much!!! and glad to get a reply you just made my week! This project had me so excited when i found it, great job with all the hard work so far. I'd LOVE to play around with prototype haha!
Is there any other channel we could talk in? Can give you my email or vice versa, also got a matrix handle etc.  I was locked out of twitter after it was bought (was inactive for a bit) and Elon's changes have made it impossible to get back in without giving up my privacy, and don't trust the privacy of DMs there anymore (not that i did much before). 

Also, so sorry to hear you having trouble with that, sounds like a huge pain in the ass. 
I apologize for being so rude! Started to make assumptions after feeling let down but i have no right to complain anyway.  I sincerely apologize.

**Comment by unsurv** [comment]
hit me up at unsurv at posteo.de
